# -*- coding: utf-8 -*-
"""NER_with_CRF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8fuWTuz3eVNuzLLUcSj7pO024_XMccT
"""

!pip install datasets==3.6.0
!pip install sklearn-crfsuite

from datasets import load_dataset

dataset = load_dataset("eriktks/conll2003")

print(dataset)

tag_names = dataset["train"].features["ner_tags"].feature.names

print(tag_names)

def to_sentences(split):
    sentences = []
    labels = []

    for item in dataset[split]:
        words = item["tokens"]
        tags = [tag_names[t] for t in item["ner_tags"]]
        sentences.append(words)
        labels.append(tags)

    return sentences, labels

train_sents, train_labels = to_sentences("train")
test_sents, test_labels = to_sentences("test")

print(train_sents[0])
print(train_labels[0])

def word2features(sent, i):
    word = sent[i]

    features = {
        'word': word,
        'lower': word.lower(),
        'is_upper': word.isupper(),
        'is_title': word.istitle(),
        'is_digit': word.isdigit(),
        'prefix2': word[:2],
        'prefix3': word[:3],
        'suffix2': word[-2:],
        'suffix3': word[-3:],
    }

    if i > 0:
        prev = sent[i-1]
        features.update({
            'prev_word': prev,
            'prev_is_title': prev.istitle(),
        })
    else:
        features['BOS'] = True

    if i < len(sent)-1:
        nxt = sent[i+1]
        features.update({
            'next_word': nxt,
            'next_is_title': nxt.istitle(),
        })
    else:
        features['EOS'] = True

    return features

def sent2features(sent):
    return [word2features(sent, i) for i in range(len(sent))]

X_train = [sent2features(s) for s in train_sents]
y_train = train_labels

X_test = [sent2features(s) for s in test_sents]
y_test = test_labels

import sklearn_crfsuite

crf = sklearn_crfsuite.CRF(
    algorithm='lbfgs',
    c1=0.1,
    c2=0.1,
    max_iterations=100
)

crf.fit(X_train, y_train)

y_pred = crf.predict(X_test)

from sklearn_crfsuite import metrics
print(metrics.flat_classification_report(y_test, y_pred))

i = 5

tokens = dataset["test"][i]["tokens"]

for t, true, pred in zip(tokens, y_test[i], y_pred[i]):
    print(f"{t:15} {true:10} {pred}")

errors = 0
total = 0

for yt, yp in zip(y_test, y_pred):
    for t, p in zip(yt, yp):
        total += 1
        if t != p:
            errors += 1

print("Error rate:", errors/total)

print(metrics.flat_f1_score(y_test, y_pred, average='weighted'))